title: Service
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: image
            field:
              max_files: 1
              container: assets
              type: assets
              display: Image
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              display: Description
              localizable: true
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: price
            field:
              default: '0'
              type: float
              display: Price
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
